# Site settings
title: Pythia Oracle
tag_text: Pythia Oracle
description: Pythia Oracle is a solo gaming tool and content generator for P&P games, built in Python and Kivy.
baseurl: 'http://exposit.github.io/pythia-oracle/'

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
